import TabCardList, { TabCardItemProps } from "./home/TabCardList";

import Banner from "./home/Banner";
import { CardListItemProps } from "./home/TabCardList/CardListItem";
import CardTitle from "./home/CardTitle";
import styles from "./index.module.scss";

const platformTags: TabCardItemProps[] = [
  {
    title: "全部平台",
    type: "all",
  },
  {
    title: "有二级",
    type: "transaction",
  },
  {
    title: "有转赠",
    type: "gift",
  },
  {
    title: "无二级无转赠",
    type: "no-transaction-no-gift",
  },
  {
    title: "APP",
    type: "app",
  },
];
const platforms: CardListItemProps[] = [
  {
    id: 1,
    logo: "https://api.iowen.cn/favicon/theone.art.png",
    name: "唯一艺术",
    desc: "",
    url: "https://theone.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 2,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/5f285-huancang.art.png",
    name: "幻藏",
    desc: "",
    url: "https://huancang.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 3,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片7.png",
    name: "iBox数字藏品",
    desc: "",
    url: "https://www.ibox.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 4,
    logo: "https://api.iowen.cn/favicon/manage.3rdplanet.cn.png",
    name: "元本空间",
    desc: "",
    url: "https://manage.3rdplanet.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 5,
    logo: "https://api.iowen.cn/favicon/artmeta.cn.png",
    name: "元艺数",
    desc: "",
    url: "https://artmeta.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 6,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/1d0d8ef541cd126e0b68bc446cbca06.jpg",
    name: "优版权",
    desc: "",
    url: "https://ubanquan.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 7,
    logo: "https://api.iowen.cn/favicon/www.nftqin.com.png",
    name: "秦宇宙",
    desc: "",
    url: "https://www.nftqin.com/active",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 8,
    logo: "https://api.iowen.cn/favicon/v3.7jft.com.png",
    name: "七级宇宙",
    desc: "",
    url: "https://v3.7jft.com/h5/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 9,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片2.png",
    name: "zTag",
    desc: "",
    url: "https://m.ztag.vip/h5",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 10,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片4.png",
    name: "ONE数字艺术",
    desc: "",
    url: "https://h5.onenft.top",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 11,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片8.png",
    name: "诺坊体数字藏品",
    desc: "",
    url: "http://www.nuofangti.com/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 12,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片3.png",
    name: "加密空间",
    desc: "",
    url: "https://crypts.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 13,
    logo: "https://api.iowen.cn/favicon/www.joy-art.cn.png",
    name: "乐享艺术J",
    desc: "",
    url: "https://www.joy-art.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 14,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/d88be2d61180973f4dac24044ea79aa.jpg",
    name: "链上艺术",
    desc: "",
    url: "https://mp.lsnft.cn/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 15,
    logo: "https://api.iowen.cn/favicon/umx.art.png",
    name: "umx.art",
    desc: "",
    url: "https://umx.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 16,
    logo: "https://api.iowen.cn/favicon/h5.skynfr.cn.png",
    name: "SKY数字版权",
    desc: "",
    url: "http://h5.skynfr.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 17,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片5.png",
    name: "IMO-蓝猫数字",
    desc: "",
    url: "https://www.lanmsz.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 18,
    logo: "https://api.iowen.cn/favicon/front.metahz.com.png",
    name: "麦塔",
    desc: "",
    url: "http://front.metahz.com/home",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 19,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片6.png",
    name: "StarArk数字文创",
    desc: "",
    url: "https://h5.stararknft.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 20,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片1.png",
    name: "草方格",
    desc: "",
    url: "https://m.caofange.com",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 21,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/6F6CAA5D-EEC3-49C1-BDC2-5CBE79992D7E.jpeg",
    name: "ADA-宇宙鸭",
    desc: "",
    url: "https://nftlabm.yuzhouya.com",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 22,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/eddf87a59f5632417a241ebb6cf5d9b.jpg",
    name: "伽作 Meta",
    desc: "",
    url: "http://meta.jiazuo.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 23,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/d3befff911939558cff2af1bf044953.jpg",
    name: "一点数藏",
    desc: "",
    url: "https://yidianart.com.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 24,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/5f30bfd30c4a5d19e2940f2ed284c3b.jpg",
    name: "哈森艺术",
    desc: "",
    url: "https://m.hasen.art/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 25,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/862a624670e5e2e358b5ad8db71178f3.jpg",
    name: "YOYO",
    desc: "",
    url: "https://www.yoyonft.vip",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 26,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/331F25F3-CD4C-4C73-AB76-FEFBB91486A2.jpeg",
    name: "云数藏",
    desc: "",
    url: "http://app.ycmeta.art",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 27,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/8d1e7acf840f63a6a0961c613919985.jpg",
    name: "HOTDOG",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 28,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/18CEA9E8-2FD5-4712-AEBD-333F5AD56398.jpeg",
    name: "薄盒",
    desc: "",
    url: "https://m.mintstech.cn",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 29,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/46EB5F31-6B4E-454D-8B46-C706B2D474AD.jpeg",
    name: "Avapunk",
    desc: "",
    url: "https://m.avapunk.com",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 30,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/776D23B5-7D40-41E9-940C-EF7D56E30AA3.jpeg",
    name: "ArtPro",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 31,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/bd946-www.foreverrealm.vip.png",
    name: "恒境",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 32,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/8c2864b81007c1f18433658246bc8d6.jpg",
    name: "秦储",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 33,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/c57b5e70a39375872d36bc1b7a77816.jpg",
    name: "千寻数藏",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 34,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/673960824724e179949fde08cdd2f03.jpg",
    name: "轻松小镇",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 35,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/44cb9eb1d2eb58ca822b664f353a75f.jpg",
    name: "鲸探",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 36,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/5932a660fb3cf3d73712f9f104263f0.jpg",
    name: "幻核",
    desc: "",
    url: "",
    type: "platform",
    tags: ["app"],
  },
  {
    id: 37,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/c45d61024d1f657f41381ccadb0d05e.jpg",
    name: "万物数字藏品",
    desc: "",
    url: "https://wx.allnfts.cn",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 38,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/0b233693b13dd550a6c17e9c79897bc.jpg",
    name: "超元空间",
    desc: "",
    url: "https://www.kuaizhanye.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 39,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/d483f4d098d5e47cbd6142bd58f2afc.jpg",
    name: "良选数字",
    desc: "",
    url: "http://h5.nftzz.cn",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 40,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/e2b93d868c5647b788ea4fe4d0bafee.jpg",
    name: "蟾宫Digital",
    desc: "",
    url: "https://m.honghuchain.com",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 41,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/3e26b9fe9b486b09551ebdb45ea9c45.jpg",
    name: "洞壹元典",
    desc: "",
    url: "https://01h5.dongyiyuandian.com/#",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 42,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/4923051f60b89b69a567d8c54efeb52.jpg",
    name: "红果数藏",
    desc: "",
    url: "https://www.nftguanfang.com/#",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 43,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/edc94fe1bc9b68d1b8bc84bf29f6aa0.jpg",
    name: "猛犸数藏",
    desc: "",
    url: "https://www.mmasc.cn",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 44,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/92e399b7fadae65b5f9fccceb97452b.jpg",
    name: "ireal",
    desc: "",
    url: "https://app.ireal.icu/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 45,
    logo: "https://api.iowen.cn/favicon/nft.9space.vip.png",
    name: "第九空间 Cosmos Art",
    desc: "",
    url: "https://app.ireal.icu/#",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 46,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/3d83ec6897050b2971ba80462e136e9.jpg",
    name: "RAEX绿洲",
    desc: "",
    url: "https://www.raex.vip",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 47,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/1ce23ce31c3e7551ebc694e725eed1b.jpg",
    name: "元星门",
    desc: "",
    url: "https://meta.nft.redph.cn",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 48,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/9c77752c94e167086f46cf0151ab77f.jpg",
    name: "良藏艺术",
    desc: "",
    url: "https://box.wiod.cn/h5",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 49,
    logo: "https://api.iowen.cn/favicon/www.redcave.com.png",
    name: "红洞数藏",
    desc: "",
    url: "https://www.redcave.com",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 50,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片11.png",
    name: "UTONMOS",
    desc: "",
    url: "http://www.artwool.cn/wp-content/uploads/2022/04/图片11.png",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 51,
    logo: "https://api.iowen.cn/favicon/meta-h5.genimous.com.png",
    name: "Meta彼岸",
    desc: "",
    url: "https://meta-h5.genimous.com",
    type: "platform",
    tags: ["no-transaction-no-gift"],
  },
  {
    id: 52,
    logo: "https://api.iowen.cn/favicon/shucang.cn.png",
    name: "数藏中国",
    desc: "",
    url: "https://shucang.cn",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 53,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片10.png",
    name: "稀象",
    desc: "",
    url: "https://shop.yes-nft.com/h5/index.html",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 54,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/图片9.png",
    name: "斑马中国",
    desc: "",
    url: "https://bmark.cn/#",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 55,
    logo: "https://api.iowen.cn/favicon/szwc.bojunwenhua.cn.png",
    name: "Hi元宇宙",
    desc: "",
    url: "https://szwc.bojunwenhua.cn",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 56,
    logo: "https://api.iowen.cn/favicon/www.simeta.world.png",
    name: "顺元数字藏品",
    desc: "",
    url: "https://www.simeta.world/pc.html",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 57,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/21119-h5.tecprove.com.png",
    name: "文博元宇宙",
    desc: "",
    url: "https://h5.tecprove.com",
    type: "platform",
    tags: ["gift"],
  },
  {
    id: 58,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/WPS图片-1.jpeg",
    name: "Metabox元気宇宙",
    desc: "",
    url: "https://www.metaboxglobal.cn/nft/index",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 58,
    logo: "https://api.iowen.cn/favicon/www.nftcn.com.cn.png",
    name: "Bigverse大元宇宙",
    desc: "",
    url: "https://www.nftcn.com.cn/pc/#/index",
    type: "platform",
    tags: ["transaction"],
  },
  {
    id: 59,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/WPS图片.jpeg",
    name: "芝士拍拍",
    desc: "",
    url: "http://m.plutoverse.cn",
    type: "platform",
    tags: ["transaction"],
  },
];
const communitiesTags: TabCardItemProps[] = [
  {
    title: "玩家社群",
    type: "group",
  },
  {
    title: "热门公众号",
    type: "wechat",
  },
];
const communities: CardListItemProps[] = [
  {
    id: 1,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/c598cae459f2ab0e096069c7ed8e130.jpg",
    name: "元宇宙/NFT交流群",
    desc: "国内最大的交流社群~",
    url: "",
    type: "group",
  },
  {
    id: 2,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/61527ef17e3e529ec1a14e93dc77121.jpg",
    name: "ABCD数字藏品社区",
    desc: "老带新，NFT新人必进社区",
    url: "",
    type: "group",
  },
  {
    id: 3,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/c12d1cf5f3a69c副本.jpg",
    name: "神话监测社群",
    desc: "国内一流监测，NFT玩家必进社群~",
    url: "",
    type: "group",
  },
  {
    id: 4,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/2722a28c72ae6ccbc63b96e816ae154.jpg",
    name: "Fu氏集团交流群",
    desc: "",
    url: "",
    type: "group",
  },
  {
    id: 5,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/05/74B0B6D9-F41D-41BF-9470-36B8B1D0C000.jpeg",
    name: "二狗玩转NFT数字藏品",
    desc: "‖干货‖黑幕‖骗局‖揭秘‖  炒作有风险，收藏需谨慎",
    url: "",
    type: "wechat",
  },
  {
    id: 6,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/057724c71df3e93903783fa1fd93b859.jpg",
    name: "NFR日常",
    desc: "国内优质数字藏品每日信息分享，每天更新日历表！亲们记得关注哦！！！",
    url: "",
    type: "wechat",
  },
  {
    id: 7,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/5cc22f9e0e2bef289811c09e334ce8a6_1.jpg",
    name: "数藏日常攻略",
    desc: "国内优质数字藏品每日信息分享，每天分享最新攻略！",
    url: "",
    type: "wechat",
  },
  {
    id: 8,
    logo: "http://www.artwool.cn/wp-content/uploads/2022/04/0e85bf3a07472a8ef6701924dba98c88.jpg",
    name: "数藏手动党",
    desc: "手动干科技！分享抢购技巧，创世空投，带你遨游元宇宙。",
    url: "",
    type: "wechat",
  },
];

const Home = () => {
  return (
    <div className={styles.container}>
      <Banner />
      <CardTitle title="数藏平台" />
      <TabCardList tabs={platformTags} items={platforms} />
      <CardTitle title="热门社区" />
      <TabCardList type="group" tabs={communitiesTags} items={communities} />
    </div>
  );
};

export default Home;
