import { NavBar as AdmNavBar } from "antd-mobile";
import { NavBarProps as AdmNavBarProps } from "antd-mobile/es/components/nav-bar";
import Head from "next/head";
import Logo from "@/components/Logo";
import styles from "./index.module.scss";

interface NavbarProps extends AdmNavBarProps {}

const Navbar = (props: NavbarProps) => {
  return (
    <>
      <Head>
        <title>Web321</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <AdmNavBar back={null} {...props}>
          <Logo />
        </AdmNavBar>
      </div>
    </>
  );
};

export default Navbar;
